"""Run Approach 1 against the 3 locked personas.

For each persona, walks Q1 -> Q2 -> Q3 -> Q4 with the doc's narrowing
schedule (300 -> 150 -> 100 -> 50 -> 10) but capped at the actual
catalog size (we have ~547, so post-Q1 = 150 holds).

Writes a markdown report to validation/approach1/results.md showing:
  - Counts at each step
  - Top-10 final picks with score breakdown
  - Top-10 at each intermediate step (for debugging)

Usage:
    cd /home/haseeb/dl-onboarding
    source venv/bin/activate
    python -m validation.approach1.run
"""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from validation.approach1.feature_scorer import UserVector, rank_tools
from validation.approach1.personas import PERSONAS, vec_summary


HERE = Path(__file__).parent
FEATURES_PATH = HERE / "catalog_features.json"
OUT_PATH = HERE / "results.md"

# Doc narrowing schedule (post each question). Tightened to actual
# catalog size at the start.
NARROW = {"Q1": 150, "Q2": 100, "Q3": 50, "Q4": 10}


def load_tools() -> list[dict]:
    feats = json.loads(FEATURES_PATH.read_text())
    return [{"slug": slug, **rec} for slug, rec in feats.items()]


def fmt_breakdown(b: dict[str, float]) -> str:
    parts = [f"{k}={v:.2f}" for k, v in sorted(b.items()) if k != "__excluded__"]
    if "__excluded__" in b:
        parts.append("EXCLUDED")
    return ", ".join(parts)


def render_user_vector(v: UserVector) -> str:
    d = asdict(v)
    lines = []
    for k in ("industry", "role", "setup_tolerance", "maturity"):
        if d.get(k):
            lines.append(f"- **{k}**: `{d[k]}`")
    if d.get("stack"):
        lines.append(f"- **stack**: {', '.join(d['stack'])}")
    if d.get("task_shape"):
        lines.append(f"- **task_shape**: {', '.join(d['task_shape'])}")
    if d.get("paradigm"):
        lines.append(f"- **paradigm**: {', '.join(d['paradigm'])}")
    return "\n".join(lines)


def render_top(ranked: list[dict], k: int) -> str:
    lines = ["| Rank | Slug | Name | Score | Top-3 dim contributions |",
             "|---:|---|---|---:|---|"]
    for i, r in enumerate(ranked[:k], 1):
        b = r["breakdown"]
        top3 = sorted(
            [(d, s) for d, s in b.items() if d != "__excluded__"],
            key=lambda kv: kv[1],
            reverse=True,
        )[:3]
        contrib = ", ".join(f"{d}={s:.2f}" for d, s in top3)
        if "__excluded__" in b:
            contrib += " · EXCLUDED"
        lines.append(
            f"| {i} | `{r['slug']}` | {r['name']} | {r['score']:.3f} | {contrib} |"
        )
    return "\n".join(lines)


def render_persona(name: str, steps: list, tools: list[dict]) -> str:
    out = [f"## {name}\n"]
    catalog_size = len(tools)
    out.append(f"Catalog size at start: **{catalog_size}**\n")

    surviving = [t["slug"] for t in tools]  # all slugs initially

    for q_label, vec in steps:
        cap = NARROW[q_label]
        # Score over the tools that survived prior steps. Soft narrowing
        # per the doc: each step re-scores the FULL surviving set with
        # the user's accumulated vector and takes top-cap.
        sub = [t for t in tools if t["slug"] in surviving]
        ranked = rank_tools(vec, sub, top_k=None)
        kept = ranked[:cap]
        surviving = [r["slug"] for r in kept]
        out.append(f"### After {q_label} — narrowed to top **{len(kept)}**\n")
        out.append("**User vector at this step:**")
        out.append(render_user_vector(vec))
        out.append("")
        out.append(f"**Top 10:**\n")
        out.append(render_top(kept, 10))
        out.append("")

    # Final top-10 with FULL breakdown
    out.append("### Final top-10 — full score breakdown\n")
    out.append("```")
    final_vec = steps[-1][1]
    final_sub = [t for t in tools if t["slug"] in surviving]
    final_ranked = rank_tools(final_vec, final_sub, top_k=10)
    for i, r in enumerate(final_ranked, 1):
        out.append(
            f"{i:2}. {r['name']:<32} score={r['score']:.3f}  "
            f"[{fmt_breakdown(r['breakdown'])}]"
        )
    out.append("```\n")
    return "\n".join(out)


def main() -> None:
    tools = load_tools()
    print(f"[run] loaded {len(tools)} feature records")

    md = ["# Approach 1 — persona run results\n"]
    md.append(
        "Generated by `validation/approach1/run.py`. Approach 1 is "
        "the hand-tagged 6-dim feature scorer per "
        "`validation/approaches.md`. Catalog and feature tags come from "
        "`catalog_features.json` (LLM-tagged via gpt-4o-mini).\n"
    )
    md.append(
        f"**Catalog size**: {len(tools)} tools.  "
        f"**Narrowing schedule**: post-Q1=150, post-Q2=100, post-Q3=50, "
        f"post-Q4=10 (matches doc).\n"
    )
    md.append("---\n")

    for name, steps in PERSONAS.items():
        md.append(render_persona(name, steps, tools))
        md.append("---\n")

    OUT_PATH.write_text("\n".join(md))
    print(f"[run] wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
